"""empty message

Revision ID: 58e9762d7ab6
Revises: e58d65b54195
Create Date: 2021-07-27 13:08:14.729948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e9762d7ab6'
down_revision = 'e58d65b54195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hired_trucks', sa.Column('phone_no', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'hired_trucks', ['phone_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hired_trucks', type_='unique')
    op.drop_column('hired_trucks', 'phone_no')
    # ### end Alembic commands ###
