"""empty message

Revision ID: 7657a9d48c5f
Revises: 33600858f7d9
Create Date: 2021-07-27 13:15:24.413468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7657a9d48c5f'
down_revision = '33600858f7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hired_trucks', ['phone_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hired_trucks', type_='unique')
    # ### end Alembic commands ###
